In [1]:
import numpy as np

In [5]:
r = np.random.randint(0,50,10)
print(r)

[ 7 11  2  3 29 46 44 33 23 38]


In [6]:
r.max()

46

In [7]:
r.argmax() # it will index of max

5

In [8]:
#create an array of 10 Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#create an array of 10 ones
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
#create an array of the integers from 10 to 50
np.arange(10,51)# shift+tab once we press shift+tab together it will show start end step





array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
#create an array of all the even integers from 10 to 50
np.arange(10,51,2)



array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
#create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#create a 3x3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# use numpy to generate a random number between 0 to 1
np.random.randn(1)

array([0.96099948])

In [22]:
#use numpy to generate an array of 25 random number sampled from a standard normal distribution
np.random.randn(25)






array([-0.07864779, -0.17476082, -0.79390811, -0.60880725,  0.4657615 ,
        0.69748271, -0.23344399, -0.20367694,  0.08986008,  1.96677002,
        0.82997353, -0.38957484,  1.92231583,  0.47966541, -1.36565931,
       -1.4594356 , -1.12489951, -0.36221506,  0.56591667, -0.53790643,
        1.54078016,  0.24463346, -1.85650815, -0.38916042,  0.53827932])

In [25]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [27]:
#create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [29]:
#now you will be given a few matrices and be asked to replicate the resulting matrix outputs
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
mat[2:,1:] # 12 to 25 index

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [33]:
mat[3,4] # get 20 from mat variable

20

In [40]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [44]:
mat[3:5] #16 to 25

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
mat.sum() # total sum

325

In [ ]:
mat.std() #standard divasion

In [46]:
#total column sum value
mat.sum(axis=0)

array([55, 60, 65, 70, 75])