In [2]:
import pandas as pd

In [12]:
data = {"Name":["keerthana","bhoomika","bhoomika","hari"],
        "Age":[23,44,32,22],
        "Location":["chennai","hydrabed","bengalore","delhi"]}
df = pd.DataFrame(data)
df

Name  Age   Location
0  keerthana   23    chennai
1   bhoomika   44   hydrabed
2   bhoomika   32  bengalore
3       hari   22      delhi

In [4]:
df.head(3)

Name  Age   Location
0  keerthana   23    chennai
1   bhoomika   44   hydrabed
2      latha   32  bengalore

In [8]:
df.tail(2)

Name  Age   Location  amount
2  latha   32  bengalore     223
3   hari   22      delhi     354

In [29]:
df["amount"] = [205,345,223,354]

In [17]:
sd = df.groupby("Name")["amount"].sum().reset_index()
sd

Name  amount
0   bhoomika     568
1       hari     354
2  keerthana     205

In [30]:
df

Name  Age   Location  amount
0  keerthana   23    chennai     205
1   bhoomika   44   hydrabed     345
2   bhoomika   32  bengalore     223
3       hari   22      delhi     354

In [31]:
df.drop("amount",axis=1,inplace=True)

In [ ]:
df3 = df.dropna(how="all") #Remove row only if all values are Nan

In [34]:
sdc = df.drop_duplicates(subset="Name",axis=1,inplace=True)  #you don't know anything while coding use shift+Tab
sdc

In [35]:
df

Name  Age Location
0  keerthana   23  chennai
3       hari   22    delhi

In [ ]:
#import pandas as pd
#df = pd.read_csv("group.csv")
#group = df.groupby(["state","city"])
#dc = group["people"].sum()
#dc

In [36]:
dcf = {"category":["groupx","groupy","groupx","groupy"],
       "Quantity":[34,10,23,45]}
dcf1 = pd.DataFrame(dcf)
dcf1

category  Quantity
0   groupx        34
1   groupy        10
2   groupx        23
3   groupy        45

In [37]:
dcf1.groupby("category").sum()

Quantity
category          
groupx          57
groupy          55

In [39]:
import numpy as np

In [59]:
dcw = {"category1":["groupx","groupy","groupx","groupy"],
       "Quantity1":[34,10,23,45]}
sd = pd.DataFrame(dcw, index = [20,21,22,23])
sd

category1  Quantity1
20    groupx         34
21    groupy         10
22    groupx         23
23    groupy         45

In [51]:
sd["amount"] = [234,45,654,np.nan]
sd

category1  Quantity1  amount
20    groupx         34   234.0
21    groupy         10    45.0
22    groupx         23   654.0
23    groupy         45     NaN

In [45]:
sd.dropna(axis=1,inplace=True)

In [49]:
sd.fillna(value=0, inplace= True)
sd

category1  Quantity1  amount
20    groupx         34   234.0
21    groupy         10    45.0
22    groupx         23   654.0
23    groupy         45     0.0

In [52]:
sd.isnull() # it will show ham many null value are there by True

category1  Quantity1  amount
20      False      False   False
21      False      False   False
22      False      False   False
23      False      False    True

In [54]:
sd["category1"].unique()

array(['groupx', 'groupy'], dtype=object)

In [66]:
#create array using Numby
s = np.zeros([2,2], dtype = int)
s1 = np.zeros([2,2], dtype = int)
s2 = np.zeros([3,3])
print(s)
print(s1)
print(s2)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [71]:
# operation on numpy Array Arithmetic operations add
a = np.array([20,30,40,20])
b = np.array([30,40,20,50])
print(a+b)
s1w = np.add(a,b)
print(s1w)
# add extra array in c
c = np.array([1,2,3,4])
print(a+b+c)
dfc = np.add(a,b,c)
print(dfc)

[50 70 60 70]
[50 70 60 70]
[51 72 63 74]
[50 70 60 70]


In [74]:
#subtraction
a1 = np.array([60,60,40,70])
b1 = np.array([20,10,20,10])
s2w = np.subtract(a1,b1)
s2w


array([40, 50, 20, 60])

In [76]:
#multiplication
a2 = np.array([60,60,40,70])
b2 = np.array([20,10,20,10])
s3w = np.multiply(a2,b2)
s3w

array([1200,  600,  800,  700])

In [77]:
#divition
a3 = np.array([60,60,40,70])
b3 = np.array([20,10,20,10])
s4w = np.divide(a3,b3)
s4w

array([3., 6., 2., 7.])

In [83]:
#numpy array index Array always start([])
a = np.arange(10,1,-2) # start num, end num, steps
a
b = a[np.array([2,3,-4])]
print(a)
b

[10  8  6  4  2]


array([6, 4, 8])

In [91]:
#numpy array slicing
h = np.arange(20)
print(h)
print(h[-8:17:1]) # start index end index steps
print(h[10:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# pandas series one dimensional array dataframe two dimensional array


In [98]:
# creating Series in pandas 
fg = np.array(["g","e","e","k","s"])
dfc = pd.Series(fg, index =[20,21,22,23,24])
dfc

20    g
21    e
22    e
23    k
24    s
dtype: object

In [100]:
#creating dataframe
fg1 = np.array(["geek","eight","asd","keertha","seeks"])
dfc1 = pd.DataFrame(fg1, index =[20,21,22,23,24],columns = ["words"])
dfc1

words
20     geek
21    eight
22      asd
23  keertha
24    seeks

In [ ]:
# filter dataframe
#df.filter(["column1","column2","column3"]).head()
#head koduththa first 5 row varum

In [107]:
# pandas create Groupby 
data1 = {"Name":["jai","anuj","jai","prince"],
         "Age":[27,23,44,33],
         "Address":["nagpur","Kanpur","Allahabad","Kannuj"],
         "Qualification":["Msc","MA","mca","bsc"]}
df1 = pd.DataFrame(data1)
sx = df1.groupby("Name")
print("Original Dataframe")
print(df1)

print("After creating Group")
sx.first()

Original Dataframe
     Name  Age    Address Qualification
0     jai   27     nagpur           Msc
1    anuj   23     Kanpur            MA
2     jai   44  Allahabad           mca
3  prince   33     Kannuj           bsc
After creating Group


Age Address Qualification
Name                             
anuj     23  Kanpur            MA
jai      27  nagpur           Msc
prince   33  Kannuj           bsc

In [109]:
result = sx["Age"].aggregate("sum")
result

Name
anuj      23
jai       71
prince    33
Name: Age, dtype: int64

In [114]:
#create dataframe with concat
fg = {"Key":["Ko","K1","K2","K3"],
       "Name":["jai","anuj","jai","prince"],
         "Age":[27,23,44,33]}
fg1 = {"Key":["Ko","K1","K2","K3"],
       "Address":["nagpur","Kanpur","Allahabad","Kannuj"],
         "Qualification":["Msc","MA","mca","bsc"]}
sdx = pd.DataFrame(fg)
sdx1 = pd.DataFrame(fg1)
dc = pd.concat([sdx,sdx1],axis=1)#concat use pannumpothu bracket open pannanum
dc

Key    Name  Age Key    Address Qualification
0  Ko     jai   27  Ko     nagpur           Msc
1  K1    anuj   23  K1     Kanpur            MA
2  K2     jai   44  K2  Allahabad           mca
3  K3  prince   33  K3     Kannuj           bsc

In [121]:
# delete particular column using column name
#df = df.loc[:,~df.columns.duplicated()] keep only first unique column
# two column duplicate ta iruntha
dc.drop(columns="Key")

Name  Age    Address Qualification
0     jai   27     nagpur           Msc
1    anuj   23     Kanpur            MA
2     jai   44  Allahabad           mca
3  prince   33     Kannuj           bsc

In [117]:
# creating dataframe merge two dataset
fg1 = {"Key":["Ko","K1","K2","K3"],
       "Name":["jai","anuj","jai","prince"],
         "Age":[27,23,44,33]}
fg2 = {"Key":["Ko","K1","K2","K3"],
       "Address":["nagpur","Kanpur","Allahabad","Kannuj"],
         "Qualification":["Msc","MA","mca","bsc"]}
sdx1 = pd.DataFrame(fg1)
sdx2 = pd.DataFrame(fg2)
dc1 = pd.merge(sdx1,sdx2, on="Key") #key unique id that's why on mention "Key"
dc1

Key    Name  Age    Address Qualification
0  Ko     jai   27     nagpur           Msc
1  K1    anuj   23     Kanpur            MA
2  K2     jai   44  Allahabad           mca
3  K3  prince   33     Kannuj           bsc

In [ ]:
#data = df.drop_duplicates(subset="column_name")
#data
#df.isnull().sum() value va kaatum like integer
#df.shape

In [ ]:
# create dataframe using join function


In [120]:
#create dataframe using join
zs = {"Name":["jai","anuj","jai","prince"],
         "Age":[27,23,44,33]}
zs1 = {"Address":["nagpur","Kanpur","Allahabad","Kannuj"],
         "Qualification":["Msc","MA","mca","bsc"]}
zc = pd.DataFrame(zs,index=["Ko","K1","K2","K3"])
zc1 = pd.DataFrame(zs1,index=["Ko","K1","K2","K3"])
cf = zc.join(zc1)
cf

Name  Age    Address Qualification
Ko     jai   27     nagpur           Msc
K1    anuj   23     Kanpur            MA
K2     jai   44  Allahabad           mca
K3  prince   33     Kannuj           bsc